### PR TITLE
Build and execute test cases using Travis CI

### PR DESCRIPTION
**Pull request by ooxi**

### CODE REVIEW

**Comment by fhunleth** [comment]
Thanks for submitting this. However, I'm not sure I understand why node and docker are needed. Wouldn't it be simpler and faster to build on whatever version of Linux Travis CI uses by default?

**Comment by ooxi** [comment]
> Thanks for submitting this. However, I'm not sure I understand why node and docker are needed. Wouldn't it be simpler and faster to build on whatever version of Linux Travis CI uses by default?

Docker is only needed if you want a reproducible environment, especially considering dependencies like `libpng-dev` and `zbar-tools`.

**Comment by fhunleth** [comment]
Sorry for the lack of response. I had intentions of revisiting this.

Based on other projects, I've mostly abandoned Travis CI. I'm going to close this since it will be pretty hard to go back. In case others are reading this and I haven't set up CI yet, GitHub Actions and CircleCI are the easiest for me to maintain currently.

**Comment by ooxi** [comment]
I agree, Travis CI is dead

**Pull request closed without merging**
